"""Canonical valid/invalid pair for schemas/run_candidates_v1.json (#29).

The valid fixture was generated by write_run_artifacts (see
test_artifacts._artifact) and frozen; the invalid fixture drops the required
`score` member of the single candidate. Both files are synthetic.
"""
from __future__ import annotations

import json
import unittest
from pathlib import Path

import jsonschema

FIXTURES = Path(__file__).resolve().parents[2] / "fixtures"
SCHEMA = json.loads(
    (Path(__file__).resolve().parents[3] / "schemas" / "run_candidates_v1.json")
    .read_text(encoding="utf-8")
)
VALIDATOR = jsonschema.Draft202012Validator(SCHEMA)


class RunCandidatesFixturesTest(unittest.TestCase):
    def test_valid_fixture_passes_current_schema(self) -> None:
        payload = json.loads((FIXTURES / "run_candidates_valid.json").read_text())
        VALIDATOR.validate(payload)
        self.assertEqual(payload["schema_version"], "RUN_CANDIDATES_V1")

    def test_invalid_fixture_fails_for_missing_score(self) -> None:
        payload = json.loads((FIXTURES / "run_candidates_invalid.json").read_text())
        with self.assertRaises(jsonschema.ValidationError) as ctx:
            VALIDATOR.validate(payload)
        self.assertIn("'score' is a required property", str(ctx.exception))


if __name__ == "__main__":
    unittest.main()
